# Generated by Django 3.1.4 on 2020-12-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_path',
            field=models.TextField(default='default url'),
            preserve_default=False,
        ),
    ]
